print("Hello, I'm Python")
name = input("What is your name?    ")
print('Hi, dear ' + name + "," + " nice to meet you")
time = input('What time is it?   ')
print(time + " is a perfect time to do something productive, " + name)
course = input("What class are you taking?    ")
print(course + " is a very important class, knowing " + course + " can be helpful in life")
mood = input("How are you feeling today?    ")
print("I am glad to hear you are feeling " + mood + "," + " I hope you will always be " + mood)
fav = input("What is your favorite tyme of year?    ")
print(fav + " is a beautiful time" + "," + " I like " + fav + " too ")
zzz = input("Are you tired?     ")
print(zzz + " ? " + " Okay, " + name + " then I will be leaving ")
print("Goodbye" + ", " + name)
