hi = ('Hello')
print(hi.upper())
print("I'm Python")
name = input("What is your name?    ")
print("Hi, dear " + name)
print("Nice to meet you")
time = input('What time is it?   ')
print(time + " is a perfect time to do something productive, " + name)
course = input("What class are you taking?    ")
print(course + " is a very important class")
print("Knowing " + course + " can be helpful in life")
mood = input("How are you feeling today?    ")
print("I am glad to hear you are feeling " + mood)
print("I hope you will always be " + mood)
fav = input("What is your favorite tyme of year?    ")
print(fav + " is a beautiful time")
print("I like " + fav + " too ")
want_to_start_a_diet = True
if want_to_start_a_diet:
    print("It's a great season to start a diet")
    print("I can motivate you, " + name)
else:
    print("It is good to keep track of your weight")
weight_in_kg = input("How much do you weigh in kilograms?  ")
weight_in_lb = float(weight_in_kg) / 0.45
print(f"You weigh {weight_in_lb} in pounds.")
scary = ("Sounds scary, right?")
print(scary.upper())
birth_year = input('I can guess how old are you. Enter the year you were born in.   ')
age = 2023 - int(birth_year)
print(age)
laugh = 'hahaha'
print(laugh.upper())
old = ("You are quite old.")
print(old)
zzz = input("Are you tired?     ")
print(zzz + " ? " + " Okay, " + name)
print("Then, I will be leaving")
print("Goodbye" + ", " + name)
end = input()
